spring:
  datasource:
    url: jdbc:mysql://localhost:3307/e.sun?useSSL=false&serverTimezone=Asia/Taipei
    username: root
    password: ''

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
